#!/bin/bash

# script to build tailscale.combined extra-small executable
#	for Linux/ARM suitable for Venus OS
#
# result is placed in the current directory

GOOS=linux
export GOOS
GOARCH=arm
export GOARCH

targetDir="/users/Kevin/GitHub/TailscaleGX"
sourceDir="/users/Kevin/GitHub/tailscale"

targetFile=tailscale
targetPath="$targetDir/$targetFile"

rm -f $targetFile

cd $sourceDir
./build_dist.sh --extra-small -o $targetPath -tags ts_include_cli ./cmd/tailscaled

cd $targetDir

# create link so tailscale executable will run as daemon also
ln -sf ./tailscale tailscaled


