#!/bin/bash

# setup for Tailscale GX
#
# provides secure access to a GX device from any remote location
# via tailscale and WireGard

standardPromptAndActions='yes'

#### following lines incorporate helper resources into this script
pkgDir=$( dirname $0 )
pkgName=$( basename $pkgDir )
pkgRoot=$( dirname $pkgDir )
if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
	source "$pkgDir/HelperResources/IncludeHelpers"
elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
else
	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
	exit 1
fi
#### end of lines to include helper resources


