#!/bin/bash

# setup for Tailscale GX
#
# provides secure access to a GX device from any remote location
# via tailscale and WireGard

standardPromptAndActions='yes'

#### following line incorporates helper resources into this script
source "/data/SetupHelper/HelperResources/IncludeHelpers"
#### end of lines to include helper resources


